# Generated by Django 5.0.4 on 2024-04-16 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiquesensations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='price',
            field=models.IntegerField(),
        ),
    ]
